name: Tarea Odoo
description: Crear una nueva tarea o requerimiento para desarrollo en Odoo
title: "[MODULO] Breve descripción de la tarea"
labels: ["tarea", "odoo"]
assignees:
  - nombre-del-usuario
body:
  - type: markdown
    attributes:
      value: |
        Completa los siguientes campos para registrar una tarea correctamente.

  - type: input
    id: titulo
    attributes:
      label: Título
      description: Título corto y claro de la tarea
      placeholder: ej. Agregar botón de validación en el formulario de facturas
    validations:
      required: true

  - type: input
    id: modulos
    attributes:
      label: Módulos relacionados
      description: Nombres de los módulos involucrados (separados por coma si hay más de uno)
      placeholder: ej. account, mi_modulo_personalizado
    validations:
      required: false

  - type: dropdown
    id: tipo_tarea
    attributes:
      label: Tipo de tarea
      description: ¿Qué tipo de tarea es?
      options:
        - Desarrollo nuevo
        - Mejora
        - Bug / Corrección
        - Investigación / Análisis
    validations:
      required: true

  - type: input
    id: rama_relacionada
    attributes:
      label: Rama relacionada
      description: Nombre de la rama donde se trabaja la tarea (si aplica)
      placeholder: ej. feature/account/boton-validacion
    validations:
      required: false

  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceptación
      description: ¿Cómo sabremos que esta tarea está correctamente implementada?
      placeholder: |
        - El botón se muestra solo cuando el estado es "Borrador"
        - Se envía un correo automático al validar
        - Se actualiza el estado correctamente
    validations:
      required: false
